export enum RecipesSortBy {
  NAME = 'NAME',
  DESCRIPTION = 'DESCRIPTION',
  ACTIVE = 'ACTIVE',
  WEIGHT = 'WEIGHT',
  PROTEINS = 'PROTEINS',
  FATS = 'FATS',
  CARBOHYDRATES = 'CARBOHYDRATES',
  CALORIES = 'CALORIES'
}
